global using BlazorTraining.Data;
global using BlazorTraining.Db;
global using BlazorTraining.Models;
global using BlazorTraining.Models.Blog;
global using BlazorTraining.Shared;
global using BlazorTraining.Pages;
global using Newtonsoft.Json;
global using BlazorTraining.Api;
global using BlazorTraining.StateContainer;
